### ISSUE TITLE
[Feat] Add Design to accident_count_by_accident_year

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#646] opened 2021-04-24 16:46 UTC
**Is your feature request related to a problem? Please describe.**
API exists. Please add design.
Please use generic Bar Chart - [See design here](https://github.com/hasadna/anyway-newsflash-infographics/issues/601) (use one color only)

**Comment by grandcohen** [comment] 2021-05-24 08:34
@atalyaalon 
isn't it duplicate of:
https://github.com/hasadna/anyway-newsflash-infographics/issues/647
?

**Comment by atalyaalon** [comment] 2021-05-26 14:07
@grandcohen
no - we have accidents count and we have injured count - they are different

**Comment by grandcohen** [comment] 2021-08-16 08:29
@atalyaalon @yuvalbl 
here's the final design for the generic bar chart. we should use that:
https://drive.google.com/file/d/17ne72PQBUtx9GwGTE13IsZNdgVjC6geY/view?usp=sharing

**Comment by atalyaalon** [comment] 2021-08-29 22:25
@grandcohen amazing
API is ready as well
Example:
```
        {
            "name": "accident_count_by_accident_year",
            "data": {
                "items": {
                    "1": {
                        "2014": 1,
                        "2015": 1,
                        "2016": 0,
                        "2017": 0,
                        "2018": 0,
                        "2019": 0,
                        "2020": 0,
                        "2021": 0
                    },
                    "2": {
                        "2016": 1,
                        "2017": 1,
                        "2019": 1,
                        "2014": 0,
                        "2015": 0,
                        "2018": 0,
                        "2020": 0,
                        "2021": 0
                    },
                    "3": {
                        "2014": 19,
                        "2015": 13,
                        "2016": 7,
                        "2017": 19,
                        "2018": 22,
                        "2019": 21,
                        "2020": 19,
                        "2021": 3
                    }
                },
                "text": {
                    "labels": {
                        "1": {
                            "name": "fatal",
                            "localized_name": "קטלנית"
                        },
                        "2": {
                            "name": "severe",
                            "localized_name": "קשה"
                        },
                        "3": {
                            "name": "light",
                            "localized_name": "קלה"
                        }
                    },
                    "title": "מספר תאונות לפי שנה, מחולקות לפי חומרה, במקטע צומת טבריה - צומת כפר נחום"
                }
            },
            "meta": {
                "rank": 8,
                "information": "כמות התאונות הקטלניות, הקשות והקלות במקטע, לפי שנת התאונה, מחולק לפי חומרת התאונה, בפרק הזמן הנבחר."
            }
        }
 ```

**Comment by yuvalbl** [comment] 2021-12-25 11:53
@atalyaalon 
wireframe is missing

**Comment by yuvalbl** [comment] 2021-12-25 12:22
API is outdated - see the spec we agreed on at https://github.com/hasadna/anyway-newsflash-infographics/issues/779#issuecomment-989009110

**Comment by liron93** [comment] 2022-01-12 14:04
1. The ANYWAY logo should be on the left side at the bottom of the page.

<img width="458" alt="צילום מסך 2022-01-12 ב-13 09 10" src="https://user-images.githubusercontent.com/96621915/149149917-7f666cd5-ab90-4425-9860-fbc4566a6244.png">

**Closed** 2022-03-30 16:16 UTC
Labels: enhancement, Priority 1
